### ISSUE TITLE
make a flush() function

### ISSUE THREAD

**Issue by KravitzLab** [KravitzLabDevices/FORCE_library#9]
`      pixels.setPixelColor(0, pixels.Color(50, 0, 0)); //Light Neopixel red
      tft.fillScreen(ST77XX_BLACK);
      tft.setCursor(40, 35);  
      tft.setTextColor(ST7735_WHITE);
      tft.println("Solenoid flush");   
      pixels.show();
      digitalWrite(SOLENOID, HIGH);
      tft.setCursor(40, 50);  
      tft.print("5..");
      delay (1000);
      tft.print("4..");
      delay (1000);
      tft.print("3..");
      delay (1000);
      tft.print("2..");
      delay (1000);
      tft.print("1..");
      delay (1000);
      digitalWrite(SOLENOID, LOW);
      tft.fillScreen(ST77XX_BLACK);`

**Comment by bamatika** [comment]
Done! Hold down both buttons for two seconds to trigger solenoid flush!
